# Generated by Django 3.1.12 on 2022-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totalemails',
            field=models.IntegerField(default=0, verbose_name='totalemails'),
        ),
    ]
